In [2]:
import pandas as pd

In [20]:
perseus_no_normalization_imputation_normal_distribution = pd.read_csv("./perseus_no_normalization_imputation_normal_distribution.txt", header=0, sep="\t")
perseus_no_normalization_imputation_normal_distribution.dropna(subset=["Student's T-test Difference 1_2", "Student's T-test q-value 1_2"], how="any", inplace=True)
positive =  perseus_no_normalization_imputation_normal_distribution[(abs(perseus_no_normalization_imputation_normal_distribution["Student's T-test Difference 1_2"]) >1) &(perseus_no_normalization_imputation_normal_distribution["Student's T-test q-value 1_2"] <0.05) ]
negative = perseus_no_normalization_imputation_normal_distribution[(abs(perseus_no_normalization_imputation_normal_distribution["Student's T-test Difference 1_2"]) <=1) | (perseus_no_normalization_imputation_normal_distribution["Student's T-test q-value 1_2"] >=0.05) ]

no_difference_ups = ["P00167", "P01133", "P02144", "P04040", "P15559", "P62937", "P63165",  "Q06830"]

difference_ups =  ["P01579", "O76070", "P63279", "P68871","P01127", "P01008", "P62988", "P10599", "P02787", "P99999", "P12081", "P51965","P10636-8", 
       "P01031", "P09211", "P02788", "P41159", "O00762", "P05413", "P00441", "P00918", "P08758", "P00915", "P01344", "P69905", 
        "P00709", "P55957", "P08263", "P61769", "P10145", "P16083", "P61626", "P02741", "P06732",
        "P01375", "P06396", "P02753", "P01112", "Q15843", "P02768"]

TP = len(positive[positive["Majority protein IDs"].str.contains("|".join(difference_ups))])
FP = len(positive) - TP

FN = len(negative[negative["Majority protein IDs"].str.contains("|".join(difference_ups))])
TN = len(negative) - FN

print(TP)
print(FP)
print(TN)
print(FN)

38
2
1906
0

In [17]:
negative[negative["Majority protein IDs"].str.contains("UPS")]

,LFQ intensity UPS1_01,LFQ intensity UPS1_02,LFQ intensity UPS1_03,LFQ intensity UPS1_04,LFQ intensity UPS2_01,LFQ intensity UPS2_02,LFQ intensity UPS2_03,LFQ intensity UPS2_04,Only identified by site,Reverse,...,Score,Intensity,MS/MS count,-Log Student's T-test p-value 1_2,Student's T-test q-value 1_2,Student's T-test Difference 1_2,Student's T-test Test statistic 1_2,Protein IDs,Majority protein IDs,id
2,33.559898,33.266960,33.075001,32.754719,32.345196,32.051254,32.303589,32.383526,NaN,NaN,...,204.49,8.567100e+10,121,2.536438,0.120395,0.893253,4.830835,P00167ups|CYB5_HUMAN_UPS,P00167ups|CYB5_HUMAN_UPS,25
11,29.016855,29.932133,29.928606,30.662548,29.065044,29.396931,29.567051,29.533228,NaN,NaN,...,89.07,1.164600e+10,47,0.669428,0.820206,0.494472,1.389400,P01133ups|EGF_HUMAN_UPS,P01133ups|EGF_HUMAN_UPS,34
15,33.358490,32.575199,32.614346,32.391178,31.315218,31.481546,31.932449,31.255749,NaN,NaN,...,323.31,6.841900e+10,216,2.484672,0.132810,1.238563,4.714710,P02144ups|MYG_HUMAN_UPS,P02144ups|MYG_HUMAN_UPS,38
20,34.735195,34.602779,34.665272,34.443321,33.732773,33.684471,33.766533,33.697994,NaN,NaN,...,323.31,2.436600e+11,566,5.030744,0.000533,0.891199,13.720747,P04040ups|CATA_HUMAN_UPS,P04040ups|CATA_HUMAN_UPS,43
37,32.099018,32.514065,32.246151,32.574070,31.624664,31.132038,31.665134,31.610653,NaN,NaN,...,208.96,6.858700e+10,224,2.629798,0.101422,0.850204,5.044952,P62937ups|PPIA_HUMAN_UPS,P62937ups|PPIA_HUMAN_UPS,61
44,33.799332,33.732166,33.686249,33.565357,33.109158,33.050980,33.103622,33.054607,NaN,NaN,...,323.31,1.441800e+11,264,4.676473,0.001079,0.616184,11.924470,Q06830ups|PRDX1_HUMAN_UPS,Q06830ups|PRDX1_HUMAN_UPS,68

In [21]:
perseus_no_normalization_imputation_normal_distribution = pd.read_csv("./no_normalization_imputation_NaN.txt", header=0, sep="\t")
perseus_no_normalization_imputation_normal_distribution.dropna(subset=["Student's T-test Difference 1_2", "Student's T-test q-value 1_2"], how="any", inplace=True)
positive =  perseus_no_normalization_imputation_normal_distribution[(abs(perseus_no_normalization_imputation_normal_distribution["Student's T-test Difference 1_2"]) >1) &(perseus_no_normalization_imputation_normal_distribution["Student's T-test q-value 1_2"] <0.05) ]
negative = perseus_no_normalization_imputation_normal_distribution[(abs(perseus_no_normalization_imputation_normal_distribution["Student's T-test Difference 1_2"]) <=1) | (perseus_no_normalization_imputation_normal_distribution["Student's T-test q-value 1_2"] >=0.05) ]

no_difference_ups = ["P00167", "P01133", "P02144", "P04040", "P15559", "P62937", "P63165",  "Q06830"]

difference_ups =  ["P01579", "O76070", "P63279", "P68871","P01127", "P01008", "P62988", "P10599", "P02787", "P99999", "P12081", "P51965","P10636-8", 
       "P01031", "P09211", "P02788", "P41159", "O00762", "P05413", "P00441", "P00918", "P08758", "P00915", "P01344", "P69905", 
        "P00709", "P55957", "P08263", "P61769", "P10145", "P16083", "P61626", "P02741", "P06732",
        "P01375", "P06396", "P02753", "P01112", "Q15843", "P02768"]

TP = len(positive[positive["Majority protein IDs"].str.contains("|".join(difference_ups))])
FP = len(positive) - TP

FN = len(negative[negative["Majority protein IDs"].str.contains("|".join(difference_ups))])
TN = len(negative) - FN

print(TP)
print(FP)
print(TN)
print(FN)

27
2
1906
1

In [15]:
negative[negative["Majority protein IDs"].str.contains("UPS")]

,LFQ intensity UPS1_01,LFQ intensity UPS1_02,LFQ intensity UPS1_03,LFQ intensity UPS1_04,LFQ intensity UPS2_01,LFQ intensity UPS2_02,LFQ intensity UPS2_03,LFQ intensity UPS2_04,Only identified by site,Reverse,...,Score,Intensity,MS/MS count,-Log Student's T-test p-value 1_2,Student's T-test q-value 1_2,Student's T-test Difference 1_2,Student's T-test Test statistic 1_2,Protein IDs,Majority protein IDs,id
0,32.560608,32.876701,32.943443,32.584213,NaN,25.527281,NaN,NaN,NaN,NaN,...,280.06,4.252800e+10,126,0.000000,1.000000,7.213961,0.000000,O00762ups|UBE2C_HUMAN_UPS,O00762ups|UBE2C_HUMAN_UPS,23
2,33.559898,33.266960,33.075001,32.754719,32.345196,32.051254,32.303589,32.383526,NaN,NaN,...,204.49,8.567100e+10,121,2.536438,0.161673,0.893253,4.830835,P00167ups|CYB5_HUMAN_UPS,P00167ups|CYB5_HUMAN_UPS,25
11,29.016855,29.932133,29.928606,30.662548,29.065044,29.396931,29.567051,29.533228,NaN,NaN,...,89.07,1.164600e+10,47,0.669428,0.822432,0.494472,1.389400,P01133ups|EGF_HUMAN_UPS,P01133ups|EGF_HUMAN_UPS,34
15,33.358490,32.575199,32.614346,32.391178,31.315218,31.481546,31.932449,31.255749,NaN,NaN,...,323.31,6.841900e+10,216,2.484672,0.177080,1.238563,4.714710,P02144ups|MYG_HUMAN_UPS,P02144ups|MYG_HUMAN_UPS,38
20,34.735195,34.602779,34.665272,34.443321,33.732773,33.684471,33.766533,33.697994,NaN,NaN,...,323.31,2.436600e+11,566,5.030744,0.000788,0.891199,13.720747,P04040ups|CATA_HUMAN_UPS,P04040ups|CATA_HUMAN_UPS,43
37,32.099018,32.514065,32.246151,32.574070,31.624664,31.132038,31.665134,31.610653,NaN,NaN,...,208.96,6.858700e+10,224,2.629798,0.134235,0.850204,5.044952,P62937ups|PPIA_HUMAN_UPS,P62937ups|PPIA_HUMAN_UPS,61
44,33.799332,33.732166,33.686249,33.565357,33.109158,33.050980,33.103622,33.054607,NaN,NaN,...,323.31,1.441800e+11,264,4.676473,0.001464,0.616184,11.924470,Q06830ups|PRDX1_HUMAN_UPS,Q06830ups|PRDX1_HUMAN_UPS,68

In [22]:
perseus_no_normalization_imputation_normal_distribution = pd.read_csv("./perseus_no_normalization_imputation_0.txt", header=0, sep="\t")
perseus_no_normalization_imputation_normal_distribution.dropna(subset=["Student's T-test Difference 1_2", "Student's T-test q-value 1_2"], how="any", inplace=True)
positive =  perseus_no_normalization_imputation_normal_distribution[(abs(perseus_no_normalization_imputation_normal_distribution["Student's T-test Difference 1_2"]) >1) &(perseus_no_normalization_imputation_normal_distribution["Student's T-test q-value 1_2"] <0.05) ]
negative = perseus_no_normalization_imputation_normal_distribution[(abs(perseus_no_normalization_imputation_normal_distribution["Student's T-test Difference 1_2"]) <=1) | (perseus_no_normalization_imputation_normal_distribution["Student's T-test q-value 1_2"] >=0.05) ]

no_difference_ups = ["P00167", "P01133", "P02144", "P04040", "P15559", "P62937", "P63165",  "Q06830"]

difference_ups =  ["P01579", "O76070", "P63279", "P68871","P01127", "P01008", "P62988", "P10599", "P02787", "P99999", "P12081", "P51965","P10636-8", 
       "P01031", "P09211", "P02788", "P41159", "O00762", "P05413", "P00441", "P00918", "P08758", "P00915", "P01344", "P69905", 
        "P00709", "P55957", "P08263", "P61769", "P10145", "P16083", "P61626", "P02741", "P06732",
        "P01375", "P06396", "P02753", "P01112", "Q15843", "P02768"]

TP = len(positive[positive["Majority protein IDs"].str.contains("|".join(difference_ups))])
FP = len(positive) - TP

FN = len(negative[negative["Majority protein IDs"].str.contains("|".join(difference_ups))])
TN = len(negative) - FN

print(TP)
print(FP)
print(TN)
print(FN)

31
2
1906
7